name: CI Pipeline

env:
  PYTHON_VERSION: '3.9'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3
        pip install -r requirements.txt || true

    - name: Run unit tests
      run: |
        python -m unittest discover -s . -p '*_test.py'


